blank_issues_enabled: true
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/DormantBillionaire/polarity-predictor-tool/security/advisories/new
    about: Please describe the issue as best (and as detailed) as you can.